# Generated by Django 4.1.5 on 2023-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiKalyaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
