# Generated by Django 4.1.5 on 2023-06-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrishiKalyaan', '0002_feedback_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_form',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
